# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0123_auto_20181003_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='FAQ'),
        ),
    ]
