# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0124_course_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learner_testimonials',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
