# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0132_person_works_to_major_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courserun',
            name='instructors',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='courses_instructed', to='course_metadata.Person'),
        ),
        migrations.AlterField(
            model_name='program',
            name='courses',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='programs', to='course_metadata.Course'),
        ),
    ]
