# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0132_person_works_to_major_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
