# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0133_auto_20190213_1129'),
    ]

    operations = [
       migrations.AddField(
            model_name='program',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, default=9999),
        ),
    ]