# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0135_program_logo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='course_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
